# Generated by Django 5.1.7 on 2025-04-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='product_id',
            field=models.CharField(default=123, max_length=400),
            preserve_default=False,
        ),
    ]
