# Generated by Django 5.1.7 on 2025-04-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_checkout_id_payment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='product_id',
        ),
    ]
