# Generated by Django 5.1.7 on 2025-04-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_credit_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checkout_id',
        ),
    ]
