# Generated by Django 5.1.7 on 2025-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upscale_credit',
            field=models.IntegerField(default=5),
        ),
    ]
