# Generated by Django 5.1.7 on 2025-04-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_upscale_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='upscale_credit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
